apiVersion: 1

deleteDatasources:
  - name: VictoriaLogs
    orgId: 1

datasources:
  - name: VictoriaLogs
    uid: victorialogs
    type: victoriametrics-logs-datasource
    access: proxy
    url: http://victorialogs:9428
    isDefault: true
    editable: false
    jsonData:
      maxLines: 500
      otelPreset:
        enabled: true
        detection:
          traceIdField: trace_id
          severity:
            field: level
            valueCase: string
            source: manual
      derivedFields:
        - name: trace_id
          matcherType: label
          url: 'trace_id:"$${__value.raw}"'
          urlDisplayLabel: Show correlated logs
